import numpy as np
from scipy.sparse import csr_matrix, coo_matrix, csc_matrix

row = np.array([0, 3, 1, 0, 0])
col = np.array([0, 3, 1, 2, 3])
data = np.array([-0.4, 1, 0, -0.6, -0.44])

A = coo_matrix((data, (row, col)), shape=(4, 4))
print("A as data " + str(A.data))
print("A as dense ")
print(A.todense())
print()

A_csr = A.tocsr()
print("A (CSR) as data " + str(A_csr.data))
print("A (CSR) as dense ")
print(A_csr.todense())
print("Minimum value with negative")
print(A_csr.data.min())
print("Minimum value of the absolute values")
print(np.abs(A_csr.data).min())
print("Maximum value without ones")
print(A_csr.data[A_csr.data != 1].max())
print("Maximum value without ones of the absolute values")
print(np.abs(A_csr.data[A_csr.data != 1]).max())

print()
A_csc = A.tocsc()
print("A (CSC) as data " + str(A_csc.data))
print("A (CSC) as dense ")
print(A_csc.todense())
print("Minimum value with negative")
print(A_csc.min())
print("Minimum value of the absolute values")
print(np.abs(A_csc.data).min())
print("Maximum value without ones")
print(A_csc.data[A_csc.data != 1].max())
print("Maximum value without ones of the absolute values")
print(np.abs(A_csc.data[A_csc.data != 1]).max())
